# Generated by Django 3.0.4 on 2020-09-16 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('checked', 'checked'), ('non-checked', 'non-checked')], default='non-checked', max_length=64),
        ),
        migrations.AlterField(
            model_name='domain',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_web', to='app.Department'),
        ),
    ]
